---
title: "p8105_hw6_sg3891"
author: Sandya Ganesh
date: 2021-12-04
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  warning = F 
  )

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
## Question 1

Load and clean data for regression analyses. Here, we will convert numeric to factor variables and check for missing data.
```{r}
birthweight = 
  read_csv("./data/birthweight.csv") %>%
  mutate(
    babysex = factor(babysex),
    babysex = fct_recode(babysex, "male" = '1', "female" = '2')
  )
```

Model with length at birth and gestational age as predictors
```{r}
model2 = lm(bwt ~ blength + gaweeks, data = birthweight)

```

Model with head circumference, length, sex, and all interactions as predictors
```{r}
model3 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight)

```

